name: kstar
favicon: null
layout_spectrum: 0.94042
typography_spectrum: 0.4139568628743291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2198428784031421
  lightness: 0.1306649507023394
  saturation: 0.6299451955128461
  rhythmicContrast: 0.0003621389623731375
purpose: []
